import { CommonModule } from '@angular/common'; import { Component, inject } from '@angular/core'; import { FormsModule } from '@angular/forms';
import { MaintenanceDataService } from '../../services/maintenance-data.service'; import { formatDateFr, statusColor } from '../../shared/maintenance.util';
@Component({selector:'app-accueil',standalone:true,imports:[CommonModule,FormsModule],template:`
<header class="page-header"><div><p class="eyebrow">Vue d'ensemble</p><h1>Tableau de bord maintenance</h1><p>Suivi synthétique du plan annuel extrait du classeur.</p></div><span class="pill readonly">Lecture seule</span></header>
<section class="metric-grid"><div class="metric"><small>Lignes suivies</small><strong>{{data.tracking.length}}</strong></div><div class="metric"><small>Terminées</small><strong>{{count('Terminé')}}</strong></div><div class="metric"><small>À traiter ce mois</small><strong>{{count('Ce mois')}}</strong></div><div class="metric"><small>Interventions</small><strong>{{data.interventions.length}}</strong></div></section>
<div class="overview"><section class="card focus"><p class="eyebrow">Focus machine</p><select class="control" [(ngModel)]="selected"><option *ngFor="let row of data.tracking" [value]="row.machine">{{row.machine}}</option></select><div class="focus-grid"><div><small>Maintenance annuelle</small><strong>{{formatDate(selectedRow?.annualDate)}}</strong></div><div><small>Statut</small><span class="pill status" [style.background]="statusColor(selectedRow!.status)">{{selectedRow?.status}}</span></div><div><small>Tâches principales</small><strong>{{data.tasksFor(selected)}}</strong></div></div></section>
<section class="card"><h2>Maintenance à venir</h2><div class="upcoming" *ngFor="let row of upcoming"><div><strong>{{row.machine}}</strong><small>{{formatDate(row.annualDate)}}</small></div><span class="pill" [style.background]="statusColor(row.status)">{{row.status}}</span></div></section></div>
<section class="card"><div class="section-title"><h2>Programme par ligne</h2><span>{{data.homeTasks.length}} lignes</span></div><div class="table-scroll"><table><thead><tr><th>Ligne</th><th>Tâches à réaliser</th><th>Statut annuel</th></tr></thead><tbody><tr *ngFor="let row of data.homeTasks"><td><strong>{{row.machine}}</strong></td><td><span class="task">{{row.tasks}}</span></td><td><span class="pill" [style.background]="statusColor(data.trackingFor(row.machine)!.status)">{{data.trackingFor(row.machine)?.status}}</span></td></tr></tbody></table></div></section>`,styles:[`.readonly{background:#dcfce7;color:#166534}.overview{display:grid;grid-template-columns:1.35fr 1fr;gap:1rem;margin:1rem 0}.focus{background:linear-gradient(135deg,#153a20,#236434);color:#fff}.focus .eyebrow{color:#86efac}.focus .control{background:#fff;max-width:320px}.focus-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-top:1.4rem}.focus-grid small,.upcoming small{display:block;font-size:.68rem;color:#bad1c0;margin-bottom:.35rem}.focus-grid strong{font-size:.95rem}.status{color:#fff}.upcoming{display:flex;justify-content:space-between;align-items:center;padding:.64rem 0;border-bottom:1px solid #edf2ee}.upcoming small{color:#718078;margin:.2rem 0 0}.section-title{display:flex;justify-content:space-between;align-items:center}.section-title span{font-size:.72rem;color:#718078}.task{font-weight:700;color:#24743a}@media(max-width:900px){.overview{grid-template-columns:1fr}.focus-grid{grid-template-columns:1fr}}` ]})
export class AccueilComponent{readonly data=inject(MaintenanceDataService);selected=this.data.tracking[0]?.machine??'';formatDate=formatDateFr;statusColor=statusColor;get selectedRow(){return this.data.trackingFor(this.selected);}get upcoming(){return this.data.tracking.filter(x=>x.status!=='Terminé').slice(0,5);}count(status:'Terminé'|'Ce mois'){return this.data.tracking.filter(x=>x.status===status).length;}}
