import { NgFor, NgIf } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { PlannerPhaseCode, PlannerStatus } from '../../models/planner.models';
import { AdminDataService } from '../../services/admin-data.service';
import { PlannerDataService } from '../../services/planner-data.service';

@Component({
  selector:'app-admin-planner',standalone:true,imports:[ReactiveFormsModule,NgFor,NgIf],styleUrl:'../admin-form.scss',
  template:`<section class="admin-page"><header><p>ADMIN / PROJECT PLANNER</p><h1>{{editIndex===null?'Add':'Edit'}} planner project</h1><span>Manage local assembly timeline projects and phase ranges.</span></header><form class="form-card" [formGroup]="form" (ngSubmit)="submit()"><div class="form-grid"><div class="field"><label>Equipment name</label><input formControlName="equipmentName"></div><div class="field"><label>Priority</label><input type="number" min="1" formControlName="priority"></div><div class="field"><label>Project code</label><input formControlName="projectCode"></div><div class="field"><label>BA number</label><input formControlName="baNumber"></div><div class="field"><label>Status</label><select formControlName="status"><option *ngFor="let status of statuses" [value]="status">{{status}}</option></select></div><div class="field"><label>Phase</label><select formControlName="currentPhase"><option *ngFor="let phase of phases" [value]="phase">{{phase}}</option></select></div><div class="field"><label>Start year / week</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:.5rem"><input type="number" min="2026" formControlName="startYear"><input type="number" min="1" max="52" formControlName="startWeek"></div></div><div class="field"><label>End year / week</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:.5rem"><input type="number" min="2026" formControlName="endYear"><input type="number" min="1" max="52" formControlName="endWeek"></div></div></div><div class="actions"><button [disabled]="form.invalid||saving">{{saving?'Saving…':(editIndex===null?'Add project':'Save changes')}}</button><button type="button" class="secondary" *ngIf="editIndex!==null" (click)="cancelEdit()">Cancel</button></div><p class="result" *ngIf="message">{{message}}</p></form><section class="records"><h2>Planner projects</h2><div class="records-scroll"><table><thead><tr><th>Project</th><th>Equipment</th><th>Priority</th><th>Phase</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let item of data.projects;let i=index"><td>{{item.projectCode}}</td><td>{{item.equipmentName}}</td><td>{{item.priority}}</td><td>{{item.currentPhase}}</td><td class="row-actions"><button (click)="edit(i)">Edit</button><button class="delete" (click)="remove(i)">Delete</button></td></tr></tbody></table></div></section></section>`
})
export class AdminPlannerComponent{
  private readonly service=inject(AdminDataService);private readonly fb=inject(FormBuilder);readonly data=inject(PlannerDataService);
  readonly phases:PlannerPhaseCode[]=['BA','BG','LZ','TR','VA','IA','VB'];readonly statuses:PlannerStatus[]=['On schedule','Delayed without impact','Delayed with impact','Available'];
  readonly form=this.fb.nonNullable.group({equipmentName:['',Validators.required],priority:[1,[Validators.required,Validators.min(1)]],projectCode:['',Validators.required],baNumber:['TBD',Validators.required],status:['On schedule' as PlannerStatus,Validators.required],currentPhase:['BA' as PlannerPhaseCode,Validators.required],startYear:[2026,Validators.required],startWeek:[1,[Validators.required,Validators.min(1),Validators.max(52)]],endYear:[2026,Validators.required],endWeek:[1,[Validators.required,Validators.min(1),Validators.max(52)]]});saving=false;message='';editIndex:number|null=null;
  submit():void{if(this.form.invalid)return;this.saving=true;this.service.upsertPlannerProject(this.form.getRawValue(),this.editIndex).subscribe(r=>{this.message=r.message;this.saving=false;this.cancelEdit(false);});}
  edit(i:number):void{const x=this.data.projects[i];const phase=x.phases[0];const code=this.phases.includes(x.currentPhase as PlannerPhaseCode)?x.currentPhase as PlannerPhaseCode:phase?.code??'BA';this.editIndex=i;this.form.setValue({equipmentName:x.equipmentName,priority:x.priority,projectCode:x.projectCode,baNumber:x.baNumber,status:x.status,currentPhase:code,startYear:phase?.startYear??2026,startWeek:phase?.startWeek??1,endYear:phase?.endYear??2026,endWeek:phase?.endWeek??1});this.message='';}
  remove(i:number):void{this.service.deletePlannerProject(i).subscribe(r=>this.message=r.message);if(this.editIndex===i)this.cancelEdit();}
  cancelEdit(clear=true):void{this.editIndex=null;this.form.reset({equipmentName:'',priority:1,projectCode:'',baNumber:'TBD',status:'On schedule',currentPhase:'BA',startYear:2026,startWeek:1,endYear:2026,endWeek:1});if(clear)this.message='';}
}
