import { Component, inject } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdminDataService } from '../../services/admin-data.service';
import { PlannerPhaseCode, PlannerStatus } from '../../models/planner.models';

@Component({
  selector:'app-admin-planner',standalone:true,imports:[ReactiveFormsModule,NgFor,NgIf],styleUrl:'../admin-form.scss',
  template:`<section class="admin-page"><header><p>ADMIN / PROJECT PLANNER</p><h1>Planner input</h1><span>Prepare equipment, priority and phase-range updates for the assembly timeline.</span></header><form class="form-card" [formGroup]="form" (ngSubmit)="submit()"><div class="form-grid"><div class="field"><label>Equipment name</label><input formControlName="equipmentName" placeholder="KTR 6-Stations"></div><div class="field"><label>Priority</label><input type="number" min="1" formControlName="priority"></div><div class="field"><label>Project code</label><input formControlName="projectCode" placeholder="PAG983"></div><div class="field"><label>BA number</label><input formControlName="baNumber" placeholder="260560 or TBD"></div><div class="field"><label>Status</label><select formControlName="status"><option *ngFor="let status of statuses" [value]="status">{{status}}</option></select></div><div class="field"><label>Phase</label><select formControlName="currentPhase"><option *ngFor="let phase of phases" [value]="phase">{{phase}}</option></select></div><div class="field"><label>Start year / week</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:.5rem"><input type="number" min="2026" formControlName="startYear"><input type="number" min="1" max="52" formControlName="startWeek"></div></div><div class="field"><label>End year / week</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:.5rem"><input type="number" min="2026" formControlName="endYear"><input type="number" min="1" max="52" formControlName="endWeek"></div></div></div><div class="actions"><button [disabled]="form.invalid||saving">{{saving?'Preparing…':'Prepare planner update'}}</button><span class="hint">Timeline validation will move to the API later.</span></div><p class="result" *ngIf="message">{{message}}</p></form></section>`
})
export class AdminPlannerComponent{
  private readonly service=inject(AdminDataService);private readonly fb=inject(FormBuilder);readonly phases:PlannerPhaseCode[]=['BA','BG','LZ','TR','VA','IA','VB'];readonly statuses:PlannerStatus[]=['On schedule','Delayed without impact','Delayed with impact','Available'];
  readonly form=this.fb.nonNullable.group({equipmentName:['',Validators.required],priority:[1,[Validators.required,Validators.min(1)]],projectCode:['',Validators.required],baNumber:['TBD',Validators.required],status:['On schedule' as PlannerStatus,Validators.required],currentPhase:['BA' as PlannerPhaseCode,Validators.required],startYear:[2026,Validators.required],startWeek:[1,[Validators.required,Validators.min(1),Validators.max(52)]],endYear:[2026,Validators.required],endWeek:[1,[Validators.required,Validators.min(1),Validators.max(52)]]});saving=false;message='';
  submit():void{if(this.form.invalid)return;this.saving=true;this.service.upsertPlannerProject(this.form.getRawValue()).subscribe(r=>{this.message=r.message;this.saving=false;});}
}
